version: "3.4"

services:
  server:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./backend:/usr/src/app

  database:
    image: database
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=root
      - POSTGRES_DB=root
