version: '3.4'

services:
  client:
    image: client
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
