version: "3.4"

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./backend:/app
    environment:
      - PGUSER=app_user
      - PGHOST=postgres
      - PGPASSWORD=1
      - PGDATABASE=app 
      - PGPORT=5432
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    logging:
      driver: none
